CREATE TABLE feed IF NOT EXISTS (
    id  VARCHAR(40) PRIMARY KEY NOT NULL,
    url VARCHAR(2048) NOT NULL
)

CREATE TABLE history IF NOT EXISTS (
    feed VARCHAR(40) NOT NULL,
    id SERIAL NOT NULL,
    diff TEXT NOT NULL,
    created DATETIME NOT NULL,
    PRIMARY KEY(feed, id)
)
